### ISSUE TITLE
How do you start new modules/repos?

### ISSUE THREAD

**Issue by bfred-it** [IonicaBizau/ama#10]
I noticed that all of your repos share the same format (.md files and readme content), do you have some tool that gives you some sort of template or is it a matter of copying, pasting, and updating?

**Comment by IonicaBizau** [comment]
Soon, I will write a blog post about that. Stay tuned. 📝

**Comment by IonicaBizau** [comment]
Uh, that *soon* took a while, but there are are: https://ionicabizau.net/blog/33-how-i-npm :tada: 

[![](http://i.imgur.com/goDMZW9.png)](https://ionicabizau.net/blog/33-how-i-npm)

For even more details, [feel free to ask](https://github.com/IonicaBizau/ama/issues/new). :speech_balloon:

**Comment by bfred-it** [comment]
That's great! Thank you! I'll try to use some of those and integrate them with `np` and my bundler

**Comment by bfred-it** [comment]
ghrepo's link is wrong

**Comment by IonicaBizau** [comment]
@bfred-it Whoups, good :eyes:! Should be fixed now.

Btw, thanks @mattdesl for that thingy. :bell: :cake:
