### ISSUE TITLE
How do you make those badges?

### ISSUE THREAD

**Issue by Khaleel** [IonicaBizau/ama#14]
How did you make those badges on your profile?

Example the ASK ME ANYTHING badge?

**Comment by vladgolubev** [comment]
@Khaleel 👉  [shields.io](http://shields.io/) 
At the very bottom you can create your own custom badge.

**Comment by Khaleel** [comment]
Thanks a lot!

**Comment by IonicaBizau** [comment]
@Khaleel Like @vladgolubev mentioned, I used [`shields.io`](https://shields.io). [This is the place](https://github.com/IonicaBizau/dotfiles/blob/a0327be9c1c76251274b0482ee3beee308d90470/blah-templates/README.ejs#L86-L105) where they are generated. 🚀 

I'm going to write soon a blog article about how I start new modules and I will probably mention this too. /cc #10 😁

**Comment by Khaleel** [comment]
Thanks a lot!
