### ISSUE TITLE
What is the meaning of life?

### ISSUE THREAD

**Issue by juandjara** [IonicaBizau/ama#17]
Please don't give me an int :pray:

**Comment by IonicaBizau** [comment]
> Please don't give me an int 🙏

`41.9999999999...` 😂 

----

Based on the Bible, I believe we are [*strangers and pilgrims* on this planet](https://www.biblegateway.com/passage/?search=Heb.11.13&version=KJV). We were not designed this way. Our world is affected by about 6000 years of sin. We see the results almost everywhere: diseases, hate, crimes, immorality etc etc. 💥 

I believe we were created by God—exactly how the Bible describes Him—and by accepting Jesus as personal saviour we are saved from the sinful state and in the end live with God forever.

As a result, we will love, respect and help everyone around us no matter what they believe or do. ✨ 
Naturally, telling others about this salvation plan makes sense. It's up to each individual accepting it or not.

We have a better land we're waiting. It won't be long 'till that will happen and it's going to be a *major version release* (including lots of bug fixes too 😁) of this planet. I really like how Peter describes this in `2 Peter 9-13`:

> The Lord is not slow concerning his promise, as some regard slowness, but is being patient toward you, because he does not wish for any to perish but for all to come to repentance.

> But the day of the Lord will come like a thief; when it comes, the heavens will disappear with a horrific noise, and the celestial bodies will melt away in a blaze, and the earth and every deed done on it will be laid bare.

> Since all these things are to melt away in this manner, what sort of people must we be, conducting our lives in holiness and godliness, while waiting for and hastening the coming of the day of God? 

> Because of this day, the heavens will be burned up and dissolve, and the celestial bodies will melt away in a blaze!

> But, according to his promise, we are waiting for new heavens and a new earth, in which righteousness truly resides.

I'm aware there are other philosophies that people agree with, making it clear to me that humans have the free will—which is a gift from God.
