### ISSUE TITLE
Would you like to make some screencasts teaching people code?

### ISSUE THREAD

**Issue by egoist** [IonicaBizau/ama#18]
[egghead.io](http://egghead.io/) (not ad.) makes me love screencasts again 😂 Because most videos there are short, brief and no bullshits. 

I know you are a mentor on codementor.io, so I wonder if you're also interested in this 😃

**Comment by IonicaBizau** [comment]
I'd like to, but the main reasons I don't do it (for now) are that I'm pretty busy and second, I don't feel comfortable to record myself talking and posting the videos online (I do record music from time to time, tho).

I like `1:1` sessions on the internet and also in the real life (I'm not good in talking to more than 2 or 3 persons at once... 😊).

I will keep this idea in mind and see if things change later. Who knows... Thanks! 😁
