### ISSUE TITLE
Support for --no-merges / --merges git flags

### ISSUE THREAD

**Issue by alechiko** [IonicaBizau/ama#21]
Hi,

I would like to pass extra options such as:

`git log --no-merges`

I tried editing git-stats-config.js with the following code:

```
module.exports = {
// Don't show merge commits
, no-merges: true
};
```

I'm not sure if i didn't do it right, or if this option simply isn't supported.

Thanks,

**Comment by IonicaBizau** [comment]
Please open such issues in the specific repositories, not here.
