### ISSUE TITLE
Do you ask your clients on code-mentor to leave a feedback?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [IonicaBizau/ama#22]
Here:
https://www.codementor.io/johnnyb/reviews

You have 866 5-start reviews.That's a lot :)
And do you use timer on a code-mentor? 

The reason why I'm asking this that I'm a code-mentor too. And I got 32 reviews.
But the thing is that most of my client use offline tip. 
If I would ask to leave feedback every time they pay me, I might have had about 100 or more. 

But I'm not sure if I should bother them with this question.

**Comment by IonicaBizau** [comment]
Sometimes yes, I tell them they can leave a rating and eventually a review. Especially if they are new Codementor users trying to figure out how the platform works. I won't feel good bothering them about leaving reviews.

> And do you use timer on a code-mentor?

Of course, that's how Codementor works. :hourglass_flowing_sand: 

> If I would ask to leave feedback every time they pay me, I might have had about 100 or more.

At the end of the day, it's not about the reviews but how happy you and they are. :blush:
