### ISSUE TITLE
How did you create the Github contributions screenshot?

### ISSUE THREAD

**Issue by XEonAX** [IonicaBizau/ama#23]
This one
[![gh-contributions](http://i.imgur.com/w6nVEgj.png)](#) 

I am especially asking about the Window frame and background.
Is this an actual screenshot or some mockup.

**Comment by IonicaBizau** [comment]
Haha! 😂 

I used [`photon-browser`](https://github.com/IonicaBizau/photon-browser) on Ubuntu, with [this background](http://simpledesktops.com/browse/desktops/2014/mar/12/las-frutas/).

The graph data is can be imported from the samples.

**Comment by XEonAX** [comment]
Thank you for your response.
