### ISSUE TITLE
How do you get enough income without working full time? 

### ISSUE THREAD

**Issue by k1r0s** [IonicaBizau/ama#25]
Hi @IonicaBizau ,

I was reading some of your posts about time managing and I need to ask you what you do to get income. I know you've spended many hours on OpenSource but how do you get the needed income to live?

I think codementor is the answer and I want to congratulate for your success. For me this is stunning:

![image](https://user-images.githubusercontent.com/6052309/33076740-e2f979a6-cecd-11e7-97c1-cbffd913cdbc.png)

Codementor really gives you enough to live without the need to sell your work force to any company?

Thanks! you're an inspiration, really :)

**Comment by IonicaBizau** [comment]
Pretty much these (pretty much in this order):

 1. [**Codementor**](https://www.codementor.io/i/jui5rnmmo) (:arrow_left: ref link)
     This is the main source of profit. I love [the flexibility](https://www.codementor.io/johnnyb/2-years-as-a-codementor-biquinqm9) it gives me and the amazing support team. :sparkling_heart: 

 2. [**Bloggify**](https://bloggify.org)
     My small business. Again, flexible, working for different clients around the world. :earth_americas: 

 3. [**Patreon**](https://patreon.com/ionicabizau)
     People set up a monthly amount which I get once a month. :rocket: 

 4. [**PayPal Donations**](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=RVXDDLKKLQRJW)
     Rarely, I get PayPal donations, but whenever I get them, they are cute! :blush:  

 5. [**Gratipay**](https://gratipay.com/share-term/)
     Currently getting ~$4 / month from there. :grin: 

 6. Rarely, **playing piano in a restaurant**, for fun... and for a free meal. :green_apple: 

Codementor works good enough, indeed!
Thanks for the kind words!
