### ISSUE TITLE
Cannot use this library in TS

### ISSUE THREAD

**Issue by cvazquezlos** [IonicaBizau/ama#28]
Hi there.

I am trying to use this library in my Angular application because I want to compare two log entries, but I am incapable to make it works properly. I am not using File System as suggested; in its case, I am using two arrays of Strings.

More exactly, my code is:

```
const LineDiff = `require('../../../../node_modules/line-diff');
const str1 = ["Hola", "Que"];
const str2 = ["ola", "k"];
console.log(LineDiff(str1, str2, 0).toString());
```

And I get an error, so I can't execute it. The path to the package is totally correct, so that is not my mistake.

What am I doing wrong?

EDIT: The library that I am trying to use is the **line-diff** one.

**Comment by IonicaBizau** [comment]
Please open an issue in the `line-diff` repository for discussing this.
