### ISSUE TITLE
Want to convert but its failling on me (newbie alert)!

### ISSUE THREAD

**Issue by m4rlof** [IonicaBizau/ama#30]
Hi, first of all thanks to make this open source! But i believe im doint something wrong with it.
lets say i want to convert this peace :  ```
"lifecycle": [
        {
            "type": "becoming-a-partner",
            "author": "Marcelo Gracietti",
            "description": "fsfsdfd\n\nsdfs\ndf\nsdf"
        } 
``` how cuold i do? and what about if i had hundreds of it. Thanks for the help

**Comment by IonicaBizau** [comment]
Please open such issues in their related repositories.
