### ISSUE TITLE
Something wrong while using this package on VSTS

### ISSUE THREAD

**Issue by roger199585** [IonicaBizau/ama#32]
I'm using 'semantic-release' to release my own npm package.
However, some error occur when I'm running `npx semantic-release --no-ci`, and the reason of the error is the url of running `git push --dry-run` is wrong.
In semantic-release they use 'gitUrlParse(repositoryUrl)' to parse the url, but the return value they get is `https://[secure]@xxxxxxx.visualstudio.com/<full_name>`.
But the url we need is `https://[secure]@xxxxxxx.visualstudio.com/<pathname>`.
What is the reason deleteing `/_git/`  in the url?

**Comment by IonicaBizau** [comment]
I guess that was fixed.
