### ISSUE TITLE
Unable to print output from Cobol code

### ISSUE THREAD

**Issue by Suvro15** [IonicaBizau/ama#33]
Hi,

I have gone through your post for establishing a bridge between Node.js & Cobol. I have GNUCobol installed and have also installed your Cobol node-package. I tried executing your sample code to print "Hello World" but the callback function does not return anything, i.e. data is undefined.
I am running this in a javascript file and have only cobol as dependency. Can you please suggest what am I doing wrong?

`var Cobol                   = require("cobol");

// Execute some COBOL 
    
    Cobol(function () {/*
                       IDENTIFICATION DIVISION.
                       PROGRAM-ID. HELLO.
                       ENVIRONMENT DIVISION.
                       DATA DIVISION.
                       FILE SECTION.
                       WORKING-STORAGE SECTION.
                        01 TEXT1 VALUE 'HOW ARE U TODAY?' PIC X(40).
                        EXEC SQL INCLUDE SQLCA END-EXEC.
                       PROCEDURE DIVISION.
                       PROGRAM-BEGIN.
                        DISPLAY "Hello world".
                       
                       PROGRAM-DONE.
                       STOP RUN.
                       */}, {
                           compileargs:{
                               free: true
                           }
                       }, function (err, data) {
        console.log("Value is: " + data);
    });` 

Output:-

C:\CobolApp>node app.js
Value is: undefined

C:\CobolApp>

**Comment by IonicaBizau** [comment]
Please open these issue in the right repository.
