### ISSUE TITLE
Getting an issue while installing on windows.

### ISSUE THREAD

**Issue by junglee372018** [IonicaBizau/ama#46]
Hi,
I am getting an issue while installing the package on windows( **Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})** ).
Is there any other package to be installed while using on windows? Can you please help me out in solving this?

Regards,
Jung Lee.

**Comment by IonicaBizau** [comment]
Please open the issue in the project repository, no in ama.
