### ISSUE TITLE
Run Terminal in web page

### ISSUE THREAD

**Issue by TheAlex2018** [IonicaBizau/ama#48]
Buna ziua,
Pot rula web-terminal in cadrul unei pagini web?
E safe?
Daca ma puteti ajuta, ma revansez cu o carte si o cafea.
Vreau sa rulez alicatii de sah in cli pe un server
www.chesscheatsheet.tk......e inca in constructie

Multumesc!
Alexandru Pascaru

**Comment by IonicaBizau** [comment]
@TheAlex2018 Da, se poate. Uneori e mai comod să faci embed la un iframe, dar se poate și direct.

Scrieți-mi pe email (`contact [at] ionicabizau [punct] net`) și ne ocupăm de problemă.
