### ISSUE TITLE
Does the edit-json-file library edit files or just add to them?

### ISSUE THREAD

**Issue by Mr-Smarty** [IonicaBizau/ama#50]
I would like to able to keep track of users and a score. I know I can use file.set when I want to add a new user, but can I edit or delete previously created fields? For example I have the json: 
```
{
  "123": "0",
  "456": "0",
  "780": "0"
} 
```
Can I change user 123's score to "1"?

**Comment by IonicaBizau** [comment]
Please follow the API reference of the module.
Best!
