### ISSUE TITLE
Your favorite GIFs

### ISSUE THREAD

**Issue by egoist** [IonicaBizau/ama#8]
eg:

![gif](https://media.giphy.com/media/6zI0KUEik37Jm/giphy.gif)

**Comment by IonicaBizau** [comment]
Currently, this is my favorite one. :joy: 

![21eeb135142462331173502484_700wa_0](https://cloud.githubusercontent.com/assets/2864371/13495927/0ccefb14-e156-11e5-9f65-13779e30759a.gif)
